test_that("fixture dataset loads", {
  path <- fixture_path("fake_gene_expression.Rds")
  skip_if_not(file.exists(path))
  obj <- readRDS(path)
  expect_true(is.list(obj))
  expect_length(obj$x_list, 4)
  expect_true("informative_genes" %in% names(obj$metadata))
  expect_true("signal_coefficients" %in% names(obj$metadata))
  expect_true("signal_shift" %in% names(obj$metadata))
  expect_length(obj$metadata$informative_genes, 12)
  expect_equal(names(obj$metadata$signal_coefficients), obj$metadata$informative_genes)
  expect_equal(names(obj$metadata$signal_shift), obj$metadata$informative_genes)
})
