// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pairwise_col_diff_cpp
NumericMatrix pairwise_col_diff_cpp(NumericMatrix x, CharacterVector col_names);
RcppExport SEXP _biomarkerPanels_pairwise_col_diff_cpp(SEXP xSEXP, SEXP col_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type col_names(col_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_col_diff_cpp(x, col_names));
    return rcpp_result_gen;
END_RCPP
}
// reference_diff_cpp
NumericMatrix reference_diff_cpp(NumericMatrix x, NumericVector ref_col, String ref_name, CharacterVector other_names);
RcppExport SEXP _biomarkerPanels_reference_diff_cpp(SEXP xSEXP, SEXP ref_colSEXP, SEXP ref_nameSEXP, SEXP other_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ref_col(ref_colSEXP);
    Rcpp::traits::input_parameter< String >::type ref_name(ref_nameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type other_names(other_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(reference_diff_cpp(x, ref_col, ref_name, other_names));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_biomarkerPanels_pairwise_col_diff_cpp", (DL_FUNC) &_biomarkerPanels_pairwise_col_diff_cpp, 2},
    {"_biomarkerPanels_reference_diff_cpp", (DL_FUNC) &_biomarkerPanels_reference_diff_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_biomarkerPanels(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
