// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pairwise_col_diff_cpp
NumericMatrix pairwise_col_diff_cpp(NumericMatrix x, CharacterVector col_names);
RcppExport SEXP _biomarkerPanels_pairwise_col_diff_cpp(SEXP xSEXP, SEXP col_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type col_names(col_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_col_diff_cpp(x, col_names));
    return rcpp_result_gen;
END_RCPP
}
// pairwise_ratios_cpp
NumericMatrix pairwise_ratios_cpp(NumericMatrix x, NumericVector feature_col, String feature_name, CharacterVector other_names);
RcppExport SEXP _biomarkerPanels_pairwise_ratios_cpp(SEXP xSEXP, SEXP feature_colSEXP, SEXP feature_nameSEXP, SEXP other_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_col(feature_colSEXP);
    Rcpp::traits::input_parameter< String >::type feature_name(feature_nameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type other_names(other_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_ratios_cpp(x, feature_col, feature_name, other_names));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_biomarkerPanels_pairwise_col_diff_cpp", (DL_FUNC) &_biomarkerPanels_pairwise_col_diff_cpp, 2},
    {"_biomarkerPanels_pairwise_ratios_cpp", (DL_FUNC) &_biomarkerPanels_pairwise_ratios_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_biomarkerPanels(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
