# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Compute pairwise difference between matrix columns (C++)
NULL

#' @title Compute pairwise ratios to a specific feature (C++)
NULL

.pairwise_col_diff_cpp <- function(x, col_names) {
    .Call('_biomarkerPanels_pairwise_col_diff_cpp', PACKAGE = 'biomarkerPanels', x, col_names)
}

.pairwise_ratios_cpp <- function(x, feature_col, feature_name, other_names) {
    .Call('_biomarkerPanels_pairwise_ratios_cpp', PACKAGE = 'biomarkerPanels', x, feature_col, feature_name, other_names)
}

